# Generated by Django 2.2.28 on 2022-07-15 16:58

from django.db import migrations, models
import djongo.models.fields
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('usertype', models.CharField(choices=[('Student', 'Student'), ('Alumni', 'Alumni'), ('Professor', 'Professor')], default='Student', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('programname', models.CharField(max_length=255)),
                ('passingyear', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('educations', djongo.models.fields.ListField(default=[], verbose_name=djongo.models.fields.EmbeddedField(model_container=user.models.education, null=True))),
                ('workexperiences', djongo.models.fields.ListField(default=[], verbose_name=djongo.models.fields.EmbeddedField(model_container=user.models.workexperience, null=True))),
                ('publications', djongo.models.fields.ListField(default=[], verbose_name=djongo.models.fields.EmbeddedField(model_container=user.models.publication, null=True))),
                ('certifications', djongo.models.fields.ListField(default=[], verbose_name=djongo.models.fields.EmbeddedField(model_container=user.models.certificate, null=True))),
                ('personalwebsite', models.URLField()),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('profileimage', models.ImageField(upload_to=user.models.pathToSave)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
