# Generated by Django 2.2.28 on 2022-07-15 16:58

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('companyname', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Marketing', 'Marketing'), ('Customer Service', 'Customer Service'), ('Human Resource', 'Human Resource'), ('Project Management', 'Project Management'), ('Business Development', 'Business Development'), ('Sales And Communication', 'Sales And Communication'), ('Design & Creative', 'Design & Creative'), ('Information Technology', 'Information Technology')], max_length=25)),
                ('type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Temporary', 'Temporary'), ('Contract', 'Contract')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('minSalary', models.IntegerField()),
                ('maxSalary', models.IntegerField()),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qulifications', models.TextField()),
                ('companydetail', models.TextField()),
                ('noOfvacancy', models.IntegerField()),
                ('url', models.URLField()),
                ('postby', djongo.models.fields.GenericObjectIdField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jobPost',
            },
        ),
    ]
